docker build -t lixinyang/cloudshell:ubuntu ./ubuntu
docker build -t lixinyang/cloudshell:centos ./centos
docker build -t lixinyang/cloudshell:debian ./debian
docker build -t lixinyang/cloudshell:alpine ./alpine
docker build -t lixinyang/cloudshell:archlinux ./archlinux
docker build -t lixinyang/cloudshell:kali ./kali
docker build -t lixinyang/cloudshell:fedora ./fedora
docker build -t lixinyang/cloudshell:opensuse ./opensuse
docker build -t lixinyang/cloudshell:rockylinux ./rockylinux