version: '3.4'

services:

    reverse-proxy:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    
    webterminal:
        image: ${DOCKER_REGISTRY-}webterminal
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - reverse-proxy
        restart: always
        volumes:
            - server:/etc/nginx

volumes:
    server: