name: cloudshell

services:

    cloudshell:
        ports:
            - "3000:80"
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/app
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        user: root

# services:

#     cloudshell:
#         image: lixinyang/cloudshell
#         ports:
#             - "80:80"
#         restart: always
#         volumes:
#             - /usr/bin/docker:/usr/bin/docker
#             - /var/run/docker.sock:/var/run/docker.sock
#         user: root