version: '3.4'

services:

    webterminal:
        image: ${DOCKER_REGISTRY-}webterminal
        ports:
            - "80:80"
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        user: root