name: container-aliyun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build UserContainer
      run: |
        cd ./container
        docker build -t cloudshell:ubuntu ./ubuntu
        docker build -t cloudshell:centos ./centos
        docker build -t cloudshell:debian ./debian
        docker build -t cloudshell:alpine ./alpine
        docker build -t cloudshell:archlinux ./archlinux
        docker build -t cloudshell:kali ./kali
        docker build -t cloudshell:fedora ./fedora
        docker build -t cloudshell:opensuse ./opensuse
        cd ..

    - name: Tag image for Aliyun
      run: |
        docker tag cloudshell:latest registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:latest
        docker tag cloudshell:ubuntu registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:ubuntu
        docker tag cloudshell:centos registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:centos
        docker tag cloudshell:debian registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:debian
        docker tag cloudshell:alpine registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:alpine
        docker tag cloudshell:archlinux registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:archlinux
        docker tag cloudshell:kali registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:kali
        docker tag cloudshell:fedora registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:fedora
        docker tag cloudshell:opensuse registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:opensuse

    - name: Push image to Aliyun
      run: |
        docker login -u=lllxy啊啊啊 -p ${{ secrets.DOCKERHUB_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:latest
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:ubuntu
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:centos
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:debian
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:alpine
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:archlinux
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:kali
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:fedora
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:opensuse
        docker logout
