name: Container-Aliyun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build UserContainer
      run: |
        cd ./container
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:ubuntu ./ubuntu
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:centos ./centos
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:debian ./debian
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:alpine ./alpine
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:archlinux ./archlinux
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:kali ./kali
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:fedora ./fedora
        docker build -t registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:opensuse ./opensuse
        cd ..

    - name: Push image to Aliyun
      run: |
        docker login -u=lllxy啊啊啊 -p ${{ secrets.DOCKERHUB_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:ubuntu
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:centos
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:debian
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:alpine
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:archlinux
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:kali
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:fedora
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/cloudshell:opensuse
        docker logout
