name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cloudshell:latest
      
    - name: Build UserContainer
      run: |
        cd ./container
        docker build -t cloudshell:ubuntu ./ubuntu
        docker build -t cloudshell:centos ./centos
        docker build -t cloudshell:debian ./debian
        docker build -t cloudshell:alpine ./alpine
        docker build -t cloudshell:archlinux ./archlinux
        docker build -t cloudshell:kali ./kali
        docker build -t cloudshell:fedora ./fedora
        docker build -t cloudshell:opensuse ./opensuse
